### ISSUE TITLE
Chat doesn't autoscroll for new messages

### ISSUE THREAD

**Issue by Jack-Papel** [ItsSammyM/mafia-rust#11]
### Bug

When a new chat message is received, and the chat column is full, the new message will be placed at the bottom, but the chat won't scroll down automatically for you to view it.

### Console output

```js
None provided
```

### Task list

- [ ] Make chat autoscroll for new messages

**Comment by ItsSammyM** [comment]
wasnt fixed as according to issue description, rather was set to autoscroll as originally implemented
