### ISSUE TITLE
Show graveyard

### ISSUE THREAD

**Issue by ItsSammyM** [ItsSammyM/mafia-rust#17]
Players should be able to see the graveyard in parallel with the role list.
A list of dead players, what night they died, and what their role is. Then if you click on their entry in the graveyard. It opens their will and other attributes

**Comment by ItsSammyM** [comment]
The menu should have 2 columns of things. Left side is role list entries, right side is graves
Should be arranged something like this


Godfather           | Night 1, Sammy (Sheriff)
Mafia Deception | Night 2, Geneveive (Cleaned)
Town Power        | Day 3, Thomas (Consort)

**Comment by Jack-Papel** [comment]
WHAAT

**Comment by Jack-Papel** [comment]
Is this resolved @ItsSammyM?
