### ISSUE TITLE
Change packets from object type to tuple type

### ISSUE THREAD

**Issue by ItsSammyM** [ItsSammyM/mafia-rust#40]
Currently all enum variants in the packet enum are either just blank variant or a struct type
If a struct type variant has only 1 feild, then it might as well be made into a tuple type.
This can be taken case by case basis

Do not do this for structs with more than 1 feild because it makes it more confusing on the front end.

**Comment by Jack-Papel** [comment]
Won't change ToClientPacket enum types, since the way we have messageListener set up is nice right now. But I'll change other types
